#!/bin/sh

# Sign a certificate signing request (a .csr file)
# with a local root certificate and key.

#export EASY_RSA="${EASY_RSA:-.}"
EASY_RSA="/home/eli/Projetos/hanokh-vpnmgr/lib/easy-rsa"
"$EASY_RSA/pkitool" --sign $*
